name: Building Blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "hello,World!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Say goodbye
              run: echo "goodbye,World!"
